🚇Various fixes for the CI (#144)
* Update CODE_OF_CONDUCT.md

Nitpicky codespell

* Update .readthedocs.yml to fix deprecation of build.image

Fix error:
> There was an error with this build The configuration key 
> "build.image" is deprecated. Use "build.os" instead to continue > > building your project. Read more at > https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os

* Update .readthedocs.yml add tools and update python section

Add required tools section
https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
Remove reprecated use system packages
https://blog.readthedocs.com/drop-support-system-packages/

* Switch to older macos runner

M1 is too fancy for now

Hopefully avoid error:
ERROR: Could not find a version that satisfies the requirement qt5-applications (from versions: none)
ERROR: No matching distribution found for qt5-applications

* Update .github/workflows/test.yml

Improve wording according to LLM

Co-authored-by: sourcery-ai[bot] <58596630+sourcery-ai[bot]@users.noreply.github.com>

---------

Co-authored-by: sourcery-ai[bot] <58596630+sourcery-ai[bot]@users.noreply.github.com>