Switch to older macos runner
M1 is too fancy for now

Hopefully avoid error:
ERROR: Could not find a version that satisfies the requirement qt5-applications (from versions: none)
ERROR: No matching distribution found for qt5-applications